### Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [2]:
import numpy as np 
import pandas as pd 

#Set the random seed for reproductivity
np.random.seed(123)

#Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [4]:
## Create Dataframe with imbalanced dataset
class_0 = pd.DataFrame({
'feature_1': np.random.normal(loc=0, scale =1, size= n_class_0),
'feature 2': np.random.normal(loc=0, scale=1, size =n_class_0),
'target': [0] * n_class_0
})

class_1= pd.DataFrame({
'feature 1': np.random.normal(loc=2, scale=1, size= n_class_1),
'feature 2': np.random.normal(loc=2, scale=1, size =n_class_1),
'target': [1]* n_class_1
})

In [7]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [8]:
df.head()

   feature_1  feature 2  target  feature 1
0  -1.085631   0.551302       0        NaN
1   0.997345   0.419589       0        NaN
2   0.282978   1.815652       0        NaN
3  -1.506295  -0.252750       0        NaN
4  -0.578600  -0.292004       0        NaN

In [9]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Up Sampling

In [10]:
# Here we increase the number of 1's by some artificial points
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [11]:
from sklearn.utils import resample
# create extra bullet points
df_minority_upsampled = resample(df_minority, replace=True,#Sample with replacement
        n_samples = len(df_majority),
        random_state=42
        )

In [12]:
df_minority_upsampled.shape

(900, 4)

In [13]:
df_minority_upsampled.head()

     feature_1  feature 2  target  feature 1
951        NaN   1.843917       1   1.125854
992        NaN   1.397425       1   2.196570
914        NaN   2.998053       1   1.932170
971        NaN   3.034197       1   2.272825
960        NaN   1.550485       1   2.870056

In [14]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [15]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Downsampling

In [16]:
## Create Dataframe with imbalanced dataset
class_0 = pd.DataFrame({
'feature_1': np.random.normal(loc=0, scale =1, size= n_class_0),
'feature 2': np.random.normal(loc=0, scale=1, size =n_class_0),
'target': [0] * n_class_0
})

class_1= pd.DataFrame({
'feature 1': np.random.normal(loc=2, scale=1, size= n_class_1),
'feature 2': np.random.normal(loc=2, scale=1, size =n_class_1),
'target': [1]* n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

#Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
# Downsampling -> Reducing Datapoints
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [19]:
from sklearn.utils import resample
# create extra bullet points
df_majority_downsampled = resample(df_majority, replace=False,#Sample with replacement
        n_samples = len(df_minority), #reduce datapoints to the length of minority
        random_state=42
        )

In [20]:
df_majority_downsampled.shape

(100, 4)

In [22]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [23]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64